// boussole service worker (OFF-1, DATA-3): precache app shell at install,
// stale-while-revalidate for the venue bundle and lazily-cached media,
// 256-entry LRU for basemap tiles (PLAN-8).
const VERSION = 'v1';

// GENERATED by tools/gen-precache.mjs 2026-09-17 — do not edit by hand
const PRECACHE = [
  "./fixtures/traces/visit-01.jsonl",
  "./index.html",
  "./manifest.webmanifest",
  "./schemas/venue.schema.json",
  "./src/components/b-app.js",
  "./src/components/b-cadran.js",
  "./src/components/b-carnet.js",
  "./src/components/b-debug.js",
  "./src/components/b-list.js",
  "./src/components/b-plan.js",
  "./src/components/b-repere.js",
  "./src/components/b-settings.js",
  "./src/components/base.js",
  "./src/lib/ambiance/engine.js",
  "./src/lib/ambiance/present.js",
  "./src/lib/cadran/state.js",
  "./src/lib/content/hash.js",
  "./src/lib/content/localize.js",
  "./src/lib/content/validate.js",
  "./src/lib/debug/session.js",
  "./src/lib/fusion/fuse.js",
  "./src/lib/fusion/registry.js",
  "./src/lib/fusion/sim.js",
  "./src/lib/geometry/affine.js",
  "./src/lib/geometry/circular.js",
  "./src/lib/geometry/geo.js",
  "./src/lib/i18n/index.js",
  "./src/lib/i18n/strings.js",
  "./src/lib/plan/draw.js",
  "./src/lib/plan/layers.js",
  "./src/lib/plan/tiles.js",
  "./src/lib/plan/viewport.js",
  "./src/lib/router.js",
  "./src/lib/sensors/audio.js",
  "./src/lib/sensors/camera.js",
  "./src/lib/sensors/geo.js",
  "./src/lib/sensors/orientation.js",
  "./src/lib/sensors/steps.js",
  "./src/lib/sensors/wakelock.js",
  "./src/lib/store/carnet.js",
  "./src/lib/store/idb.js",
  "./src/lib/store/observable.js",
  "./src/lib/tiers.js",
  "./src/lib/types.js",
  "./src/main.js",
  "./sw.js"
];
// END GENERATED

const SHELL = `boussole-shell-${VERSION}`;
const CONTENT = 'boussole-content'; // venue bundle + media (stale-while-revalidate)
const TILES = 'boussole-tiles';      // basemap LRU (PLAN-8)
const TILE_LRU_MAX = 256;

self.addEventListener('install', (e) => {
  e.waitUntil(caches.open(SHELL).then((c) => c.addAll(PRECACHE)));
  self.skipWaiting();
});

self.addEventListener('activate', (e) => {
  e.waitUntil((async () => {
    const keys = await caches.keys();
    await Promise.all(keys
      .filter((k) => k.startsWith('boussole-shell-') && k !== SHELL)
      .map((k) => caches.delete(k)));
    await self.clients.claim();
  })());
});

self.addEventListener('fetch', (e) => {
  const url = new URL(e.request.url);
  const isTile = url.hostname.includes('openstreetmap') || url.pathname.includes('/tiles/');
  const isShell = url.origin === location.origin && PRECACHE.some((p) => url.pathname.endsWith(p.slice(1)));
  const isContent = url.origin === location.origin && !isShell;

  if (isTile) {
    e.respondWith((async () => {
      const cache = await caches.open(TILES);
      const hit = await cache.match(e.request);
      if (hit) return hit; // offline-first for tiles
      try {
        const res = await fetch(e.request);
        if (res.ok) {
          await cache.put(e.request, res.clone());
          const keys = await cache.keys();
          for (let i = 0; i < keys.length - TILE_LRU_MAX; i++) await cache.delete(keys[i]);
        }
        return res;
      } catch {
        return hit ?? Response.error();
      }
    })());
    return;
  }
  if (isShell) {
    e.respondWith(caches.match(e.request).then((hit) => hit ?? fetch(e.request)));
    return;
  }
  if (isContent && e.request.method === 'GET') {
    // stale-while-revalidate (ARCH-3)
    e.respondWith((async () => {
      const cache = await caches.open(CONTENT);
      const hit = await cache.match(e.request);
      const fresh = fetch(e.request).then((res) => {
        if (res.ok) cache.put(e.request, res.clone());
        return res;
      }).catch(() => hit);
      return hit ?? fresh;
    })());
  }
});

