// boussole service worker — stub (OFF-1 precache lands in Phase 5,
// generated by tools/gen-precache.mjs; do not hand-edit the list).
const VERSION = 'dev-0';

self.addEventListener('install', (e) => self.skipWaiting());
self.addEventListener('activate', (e) => self.clients.claim());
self.addEventListener('fetch', () => { /* network passthrough for now */ });
